53 Content menu done
frostsergei/MSE-2023-msm-industrial_design-19 pull request #70
Opened 2023-05-03 08:43 UTC by Vladis4791

2023-05-03 09:33 UTC, PodoprigoraIvan commented
@Vladis4791 Поправь ошибки в csproj:
![image](https://user-images.githubusercontent.com/57725067/235880921-18821c07-76b2-4d48-b68c-570e629227aa.png)

2023-05-03 12:24 UTC, TheShenk commented
1. Уберите, пожалуйста, текст "Навигация" и растяните содержание на всю левую область. При этом содержание должно должно занимать всю область при изменении размеров окна.

![изображение](https://user-images.githubusercontent.com/34752373/235913839-57770004-af1b-44a2-90d2-1474062b1f70.png)

2. Кажется, что в ситуации, когда содержание не помещается нужно давать возможность прокрутки (возможно, используя что-то такое: https://learn.microsoft.com/ru-ru/dotnet/api/system.windows.forms.scrollbar). Например, на скрине нельзя переместиться к потребителям.

![изображение](https://user-images.githubusercontent.com/34752373/235914209-72ae2b22-f645-41a1-bb1f-aee56bd16da9.png)

2023-05-03 17:11 UTC, PodoprigoraIvan requested changes
@Vladis4791 
1. Разве нужно выделять текст с названием прибора по клику?
2. На фоне цвета выделения тяжело читать текст.
![image](https://user-images.githubusercontent.com/57725067/235988340-a0396f45-4fe0-4590-a481-0bc8cc575790.png)

2023-05-04 05:14 UTC, Vladis4791 commented
Я не знаю, как убрать синий цвет, пускай пока так будет

2023-05-04 06:03 UTC, TheShenk approved these changes

2023-05-04 06:04 UTC, merged